### ISSUE TITLE
Full Stack Proposal Feedback

### ISSUE THREAD

**Issue by eshoule** [Jathrone/Slick#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [ ] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [ ] all links route the correct page

## Comments
- [ ] your backend link on the main wiki page does not link to the right place (it just opens a new page)
---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [ ] Includes two to three detailed bullets on functionality and presentation of feature
- [ ] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
- [ ] We should parse down some of the bullet points under the MVPs. Remove react, star and reference other uses from your channel's MVP. Creating the channels itself is enough for the scope of this project. I would just put the following bullets - Create new channels and group chats, Smooth navigation between chatrooms, Slack-like styling.
- [ ] Remove sharing code snippets from your DMs - creating live chat and DMs is enough for now. You can focus on other bonus features once you finish the core functionality.
- [ ] For messages I'd but bullets along the line of - send messages, see a list of sent messages, delete own messages, update own messages.
---

# Database Schema

- [x] Contains correct datatypes
- [ ] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [ ] unique
    - [x] indexed
    - [ ] foreign key
- [ ] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - [ ] foreign key and table name are lowercased, snake_cased and `back_ticked`
- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are lowercased, snake_cased and `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
- [ ] Some of your column names are missing underscores
- [ ] If you want to store images in AWS, you don't need an image url in your DB - you would instead use ActiveStorage and associations
- [ ] Remove all of your starred and react stuff.
- [ ] subscriptions should probably be unique
- [ ] If you want, you could just have one channels table where you have a boolean for whether it's a DM or not - they have similar functionality. Then for your messages you wouldn't need a `parent_type`. You can also keep what you have.
---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [ ] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [ ] Top level slices
        - [x] `entities`
        - [x] `session`
        - [ ] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
- [ ] Remove starred and react emojis stuff 
- [ ] Channels should probably have `creator_id`
- [ ] I might move current chat to be under the `ui` slice of state
---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
- [ ] `CREATE` should be `POST` under your messages routes.
- [ ] I don't think you need this `GET /api/messages/:id/messages` (for thread messages; other messages should load with corresponding channels and direct messages) - When you show a channel/DM, all of the messages for that channel will also be shown. 
---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments
- [ ] What's the comments under `/*/messages`?
- We should discuss frontend routes/components further on Tuesday.

**Comment by eshoule** [comment]
Good job! Please address the above unchecked items/comments. We will also meet at some point on Tuesday to talk over the proposal/answer your questions.

**Comment by Jathrone** [comment]
I have resolved all of the issues in wiki. Because of functional differences among channel, DM, and threads (static versus dynamic participant composition, message sharing permissions, ability to comment on messages), I feel more comfortable leaving them as separate entities for now. I will look into refactoring once more functionality have been built. 

`GET /api/messages/:id/messages` are made for the display of threads in the side content section
